name: Update AMI IDs

on:
  workflow_dispatch:
    inputs:
      version:
        required: true
        type: string
        description: Release version tag (ex. 12.1.0)

  workflow_call:
    inputs:
      version:
        required: true
        type: string
        description: Release version tag (ex. 12.1.0)

permissions:
  contents: write
  pull-requests: write
  id-token: write

jobs:
  update-ami-ids:
    name: Update AMI IDs
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        # with:
        #   ref: ${{ vars.GITHUB_REF }}

      - name: Assume AWS role
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region:  us-west-2
          role-to-assume: "arn:aws:iam::126027368216:role/tf-teleport-ami-gha-role"
          role-session-name: "gha-update-ami-ids-${{ github.run_number }}"

      - name: Update AMI IDs and create PR
        run: |
          git config --global user.email "noreply@github.com"
          git config --global user.name "GitHub"
          TELEPORT_VERSION=${{ inputs.version }} make -C assets/aws create-update-pr
        env:
          GITHUB_TOKEN: ${{ github.token }}

      # - name: Create pull request
      #   if: steps.get_release.outputs.release == 'latest' || inputs.version != ''
      #   uses: peter-evans/create-pull-request@v4
      #   with:
      #     token: ${{ github.token }}
      #     commit-message: "[auto] Update AMI IDs for ${{ inputs.version }}"
      #     title: "[auto] Update AMI IDs for ${{ inputs.version }}"
      #     committer: GitHub <noreply@github.com>
      #     branch: ami-auto-branch
      #     branch-suffix: timestamp
      #     delete-branch: true
      #     labels: automated, terraform
